workflows:
  android-debug-workflow:
    name: Android debug workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install dependencies
        script: flutter packages pub get
      - name: Flutter build debug apk
        script: |
          flutter build apk --debug
         
    artifacts:
      - build/**/outputs/flutter-apk/*.apk
  android-workflow:
    name: Android release workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      java: 17
      groups:
        - android_key_info # Includes (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION)
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Set up keystore
        script: echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/codemagic.keystore
      - name: Install dependencies
        script: flutter packages pub get
      - name: Flutter build aab and automatic versioning
        script: |
          flutter build appbundle --release \
      - name: Flutter build apk
        script: |
          flutter build apk --release \
          
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/flutter-apk/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
        
  web-workflow:
    name: Web workflow
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter build webapp
        script: |
          flutter config --enable-web
          flutter build web --release
          cd build/web
          7z a -r ../web.zip ./*
    artifacts:
      - build/web.zip
      - flutter_drive.log

  ios-workflow:
    name: iOS release workflow
    instance_type: mac_mini_m1
    # labels:
    #   - ${CLIENT_ID} # Helpful when you open your Codemagic's builds page  
    environment:
      flutter: stable
      groups:
        - ios_credentials # Includes 4 things: $APP_STORE_CONNECT_PRIVATE_KEY, $APP_STORE_CONNECT_KEY_IDENTIFIER, $APP_STORE_CONNECT_ISSUER_ID, $CERTIFICATE_PRIVATE_KEY
      vars:
        XCODE_SCHEME: "Runner"

    scripts:
      # - *get_assets #Getting client assets from S3 bucket

      # - name: Change iOS app name
      #   script: /usr/libexec/PlistBuddy -c "Set :CFBundleName $APP_NAME" -c "Set :CFBundleDisplayName $APP_NAME" ios/${XCODE_SCHEME}/Info.plist

      # - name: Set bundle id
      #   script: sed -i '' -e 's/PRODUCT_BUNDLE_IDENTIFIER \= [^\;]*\;/PRODUCT_BUNDLE_IDENTIFIER = '${BUNDLE_ID}';/' ios/${XCODE_SCHEME}.xcodeproj/project.pbxproj

      # - name: Change iOS icons
      #   script: cp -r ./$ASSETS_FOLDER/$IOS_ASSETS_FOLDER ios/${XCODE_SCHEME}/Assets.xcassets/
      
      # - name: Set client .env file
      #   script: echo $DOTENV | base64 --decode > assets/client.env
      
      # - name: Set main image # An image that being used in this sample project
      #   script: cp -r ./$ASSETS_FOLDER/hero.png assets/hero.png
      
      - name: Install pods
        script: find . -name "Podfile" -execdir pod install \;      
      
      - name: iOS code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      
      - name: Install dependencies
        script: flutter packages pub get      
      
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts: 
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log    
      - test-results/flutter.json
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:      
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      # email: 
      #   recipients:
      #     - anassalhi31@gmail.com
      # - name: IOS build process with build ID, Flutter build ipa and automatic versioning
      #   script: |
      #     BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1))
      #     flutter build ipa --release \
      #     --build-name=1.0.$BUILD_NUMBER \
      #     --build-number=$BUILD_NUMBER\
      #     --export-options-plist=/Users/builder/export_options.plist
    